/**
 * Created by shitengteng on 2016/12/30.
 */
/*
 * 这里定义所有的action类型
 *
 */
// Post
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_SUBREDDIT = 'SELECT_REDDIT'
export const INVALIDATA_REDDIT = 'INVALIDATA_REDDIT'
export const RECEIVE_DELETE_DATA='RECEIVE_DELETE_DATA'
export const SEND_WECHAT_REQUEST='SEND_WECHAT_REQUEST'

//order
export const REQUEST_ORDER_QUANTITY='REQUEST_ORDER_QUANTITY'
export const GET_A_SINGLE_NUMBER='GET_A_SINGLE_NUMBER'


//operation
//Delete after pop
export const SEND_DELETE_REQUEST='SEND_DELETE_REQUEST'
export const DELETE_DATA = 'DELETE_DATA'

//mark
export const CHANGE_NOTES ='CHANGE_NOTES'

//GetData
export const GET_DATA_START = 'GET_DATA_START'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const TEST_DISPATCH = 'TEST_DISPATCH'
//PostData
export const POST_DATA_START = 'POST_DATA_START'
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'
export const ACCESS_TO_LOISTICS='ACCESS_TO_LOISTICS'
export const SUCCESS_TO_LOISTICS='SUCCESS_TO_LOISTICS'

//Prompt
export const OPEN_THE_WINDOW ='OPEN_THE_WINDOW'
export const CLOSE_THE_WINDOW ='CLOSE_THE_WINDOW'


// Timer
export const START = 'START'
export const STOP = 'STOP'
export const RESET = 'RESET'
export const TIMER = 'TIMER'




//DeliverGoods
//select
export const  SELECT_RECEIVE_DATA ='SELECT_RECEIVE_DATA'
export const  CHECK_ALL ='CHECK_ALL'
export const  SELECT_THE_RADIO='SELECT_THE_RADIO'
//logistics
export const  LOGISTICS_RECEIVE_DATA ='LOGISTICS_RECEIVE_DATA'
export const SELECT_LOGISTICS_COMPANY='SELECT_LOGISTICS_COMPANY'
export const NUMBER_OF_LOGISTICS='NUMBER_OF_LOGISTICS'
export const REDUCTION_SELECTION='REDUCTION_SELECTION'
export const MAIL_FROM_MENTIONING='MAIL_FROM_MENTIONING'
export const CONTACT_INFORMATION='CONTACT_INFORMATION'













